language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
install:
- pip install -U platformio
script:
- cd mkrwan1300 && cp thermostat/credentials.sample.h thermostat/credentials.h && pio run && cd ..
- cd thethingsuno && cp thermostat/credentials.sample.h thermostat/credentials.h && pio run && cd ..
