language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
install:
- pip install -U platformio
script:
- cd mkrwan1300 && pio run && cd ..
- cd thethingsuno && pio run && cd ..
